name: Issue 

on: workflow_dispatch
  issues:
    types: opened

jobs:
  notify:
    runs-on: ubuntu-latest
    steps: 
      - name: Afficher un message
        run: echo "Issue créée : ${{ github.event.issue.title }}"
