name: Push or Pull
on: [push, pull_request]

env:
    PUSH: C'est un Push
    PULL_REQUEST: C'est un Pull


jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Push
              run: echo "$PUSH"

    pull_request:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Pull_request
              run: echo "$PULL_REQUEST"
