name: Amnesia
on: workflow_dispatch

env: 
    NAME: Brendan

jobs: 
    say_hello:
        runs-on: ubuntu-latest
        env: 
            ENTREPRISE: Hetic
        steps: 
           - name: "Dit bonjour"
             if: ${{ env.NAME != 'Brendan'}}
             run: echo "Salut, vous n'etes pas Brendan"
           - name: "Hello Brendan"
             if: ${{ env.NAME == 'Brendan'}}
             run: echo "Salut $NAME, ravi de vous revoir"
        